### ISSUE TITLE
[Feature Request] Hide "On this page" when there's only an overview

### ISSUE THREAD

**Issue by melissahenderson** [interledger/interledger.org-learn#7]
* /introduction/watch-introduction-video/
* /introduction/share-your-thoughts/
* /digital-financial-inclusion/why-we-need-to-take-action/
* /building-with-interledger/building-towards-the-future/
* /interledger-technology/what-is-the-ilp/
* /interledger-technology/visualizing-the-transfer-of-ilp-packets/
* /interledger-technology/an-analogy-to-the-postal-service/ (may get addtl content that creates more sections)
* /interledger-technology/designed-for-simplicity/ (may get addtl content that creates more sections)
* /interledger-technology/lets-hear-from-you/

**Comment by melissahenderson** [comment]
https://github.com/withastro/starlight/discussions/1675

**Comment by huijing** [comment]
Can implement modified version of https://github.com/WICG/webmonetization/pull/445/commits/45898b3837e20962bbff07aa9241d8849b896711 here.
